let cart = JSON.parse(localStorage.getItem('shopzoneCart') || '[]');
let currentStep = 1;
const money = n => `$${n.toFixed(2)}`;
function totals(){const subtotal=cart.reduce((s,x)=>s+x.price*x.quantity,0);const discount=subtotal>=100?10:0;const shipping=subtotal>0?10:0;return {subtotal,discount,shipping,total:subtotal-discount+shipping}}
function renderCart(){const wrap=document.getElementById('cartItems');wrap.innerHTML='';if(!cart.length){document.getElementById('emptyCart').hidden=false;document.querySelector('#checkoutStep1 .summary-card').style.opacity='.7'}else{document.getElementById('emptyCart').hidden=true;cart.forEach((item,i)=>{const row=document.createElement('div');row.className='cart-item';row.innerHTML=`<img src="${item.image}" alt="${item.name}"/><div class="cart-item-info"><h3>${item.name}</h3><p>Quantity: ${item.quantity}</p><p>Size: ${item.size}</p><p>Color: ${item.color}</p><strong>${money(item.price)}${item.quantity>1?' × '+item.quantity:''}</strong></div><button class="remove-item" data-index="${i}" title="Remove">🗑</button>`;wrap.appendChild(row)})}document.querySelectorAll('.remove-item').forEach(b=>b.onclick=()=>{cart.splice(Number(b.dataset.index),1);save();renderCart()});updateSummary();document.getElementById('cartCount').textContent=cart.reduce((s,x)=>s+x.quantity,0)}
function updateSummary(){const t=totals();document.getElementById('subtotal').textContent=money(t.subtotal);document.getElementById('discount').textContent=`-${money(t.discount)}`;document.getElementById('shipping').textContent=money(t.shipping);document.getElementById('total').textContent=money(t.total);document.querySelectorAll('.subtotal-copy').forEach(x=>x.textContent=money(t.subtotal));document.querySelectorAll('.discount-copy').forEach(x=>x.textContent=`-${money(t.discount)}`);document.querySelectorAll('.shipping-copy').forEach(x=>x.textContent=money(t.shipping));document.querySelectorAll('.total-copy').forEach(x=>x.textContent=money(t.total))}
function save(){localStorage.setItem('shopzoneCart',JSON.stringify(cart))}
function showStep(n){currentStep=n;[1,2,3].forEach(i=>{document.querySelector(`[data-step="${i}"]`).classList.toggle('active',i===n);document.getElementById(`checkoutStep${i}`).hidden=i!==n});document.getElementById('orderSuccess').hidden=true;window.scrollTo({top:0,behavior:'smooth'})}
document.getElementById('toAddress').onclick=()=>{if(!cart.length){showToast('Your cart is empty. Add a product first.');return}showStep(2)};
document.getElementById('backToCart').onclick=()=>showStep(1);
document.getElementById('addressForm').onsubmit=e=>{e.preventDefault();localStorage.setItem('shopzoneAddress',JSON.stringify(Object.fromEntries(new FormData(e).entries())));showStep(3)};
document.getElementById('backToAddress').onclick=()=>showStep(2);
document.getElementById('placeOrder').onclick=()=>{const method=document.querySelector('input[name="payment"]:checked').value;localStorage.setItem('shopzoneLastPayment',method);localStorage.removeItem('shopzoneCart');cart=[];document.querySelectorAll('.checkout-layout').forEach(x=>x.hidden=true);document.querySelectorAll('.checkout-steps .step').forEach(x=>x.classList.remove('active'));document.getElementById('orderSuccess').hidden=false;document.getElementById('cartCount').textContent='0'};
renderCart();
